import { Button, HorizontalBox, VerticalBox, Slider, ScrollView, LineEdit } from "std-widgets.slint";

import { TrackSelector, TrackInfo } from "./trackselector.slint";

export component Player inherits Rectangle {
	callback toggle_pause();
    callback skip_by(int);
    callback seek(float);
    callback user_activity();
    callback back();
    callback select_audio_track(int);
    callback select_subtitle_track(int);
    callback close_player();

    callback next();
    callback previous();

    width: 100%;
    height: 100%;
    background: black;

    // Player Properties
    in property <image> video_frame;
    in property <bool> is_paused: false;
    in property <float> progress: 0.0;
    in property <string> time_pos: "00:00";
    in property <string> duration: "00:00";
    in property <bool> controls_visible: true;

    in property <bool> has_next;
    in property <bool> has_previous;

    in property <[TrackInfo]> audio_tracks: [];
    in property <[TrackInfo]> subtitle_tracks: [];
    in property <string> audio_track_name: "Default";
    in property <string> subtitle_track_name: "None";

    Image {
        source: root.video_frame;
        width: 100%;
        height: 100%;
        image-fit: contain;
    }

    TouchArea {
        // Keep visibility on click
        clicked => { root.user_activity(); }
        // Move activity
        pointer-event(evt) => { root.user_activity(); }
    }

    // Overlay Controls
    if root.controls_visible : Rectangle {
        background: #00000088;
        height: 120px;
        width: 100%;
        y: parent.height - self.height;

        VerticalLayout {
            padding: 20px;
            spacing: 10px;

            // Progress Bar
            HorizontalLayout {
                spacing: 15px;
                
                Text { text: root.time_pos; color: white; vertical-alignment: center; }
                
                Slider {
                    value: root.progress;
                    minimum: 0;
                    maximum: 100;
                    changed(val) => { root.seek(val); }
                }
                
                Text { text: root.duration; color: white; vertical-alignment: center; }
            }

            // Controls
            HorizontalLayout {
                spacing: 20px;
                alignment: center;

                Button {
                    text: "<<";
                    clicked => { root.previous() }
                    enabled: root.has_previous;
                }

                Button {
                    text: "← 10s";
                    clicked => { root.skip_by(-10); }
                }

                Button {
                    text: root.is_paused ? "▶" : "⏸";
                    width: 60px;
                    clicked => { root.toggle_pause(); }
                }

                Button {
                    text: "10s →";
                    clicked => { root.skip_by(10); }
                }

                Button {
                    text: ">>";
                    clicked => { root.next() }
                    enabled: root.has_next;
                }
                        
                Rectangle { width: 40px; } // spacer

                TrackSelector {
                    label: "Audio:";
                    tracks: root.audio_tracks;
                    current_name: root.audio_track_name;
                    select_track(id) => { root.select_audio_track(id); }
                }

                TrackSelector {
                    label: "Subtitles:";
                    tracks: root.subtitle_tracks;
                    current_name: root.subtitle_track_name;
                    select_track(id) => { root.select_subtitle_track(id); }
                }

                Rectangle { width: 40px; } // spacer

                Button {
                    text: "Close";
                    clicked => { root.close_player(); }
                }
            }
        }
    }
}
